### ISSUE TITLE
Ask 

### ISSUE THREAD

**Issue by ekonik3** [srctfux/gma3k6_win10_patch#1]
Do i have to delete system app and windowsapp in order to install this driver?

**Comment by srctfux** [comment]
No, basically the patch disables [MSI](https://en.wikipedia.org/wiki/Message_Signaled_Interrupts) and 3D acceleration to avoid VIDEO_TDR_FAILURE, forcing system apps to use software rendering.
Web browsers blacklist 3D calls to this and other buggy chipsets, MS could do the same with its apps.
